targetInstance: ${TEST_URL:http://localhost:8095}

s2s-url: ${S2S_URL_FOR_TESTS:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

s2s-name: rd_caseworker_ref_api
scope-name: openid profile roles manage-user create-user search-user

idam.api.url: ${IDAM_URL:https://idam-api.aat.platform.hmcts.net}
oauth2.client.secret: ${CA_REF_OAUTH2_CLIENT_SECRET:}
idam.auth.clientId: ${CA_REF_OAUTH2_CLIENT_ID:}
idam.auth.redirectUrl: ${OAUTH2_REDIRECT_URI:https://rd-caseworker-ref-api-aat.service.core-compute-aat.internal/oauth2redirect}
s2s-secret: ${CASEWORKER_REF_API_S2S_SECRET:}
userProfUrl: http://rd-user-profile-api-aat.service.core-compute-aat.internal
locationRefDataUrl: http://rd-location-ref-api-aat.service.core-compute-aat.internal
### staff Upload File configuration
staff_upload_file: ${STAFF_UPLOAD_FILE:false}
idam_role_mapping_file: ${IDAM_ROLE_MAPPING_FILE:true}


#######
postgres.host_name: ${FUNC_DATABASE_HOST}
postgres.name: ${FUNC_DATABASE_NAME}
postgres.user: ${FUNC_DATABASE_USER}
postgres.password: ${FUNC_DATABASE_PASS}
postgres.port: ${FUNC_DATABASE_PORT}
#######